version: '3'

networks:
  net_django:
    driver: bridge

services:
  db:
    image: postgres:15.3
    hostname: ${POSTGRES_HOSTNAME}
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
      - ${POSTGRES_DOCKER_PORT}:${POSTGRES_PORT} # 54320 add zero for connection to db manager (dbeaber) to docker
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    networks:
      - net_django

  web:
    hostname: ${APP_HOSTNAME}
    container_name: ${DJANGO_CONTAINER_NAME}
    tty: true
    build: .
    command: python manage.py runserver ${APP_HOST}:${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - net_django
